application: iron-puzzler
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /admin
  script: admin.py

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

builtins:
- datastore_admin: on
